# Generated by Django 2.0.2 on 2018-03-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_ocuser_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unsubscribeuser',
            options={'verbose_name': 'Unsubscriber', 'verbose_name_plural': 'Unsubscribers'},
        ),
    ]
