# Generated by Django 2.0.2 on 2018-04-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_emailpixeluser_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailpixeluser',
            name='m_id',
            field=models.IntegerField(default=0, verbose_name='Meeting ID'),
        ),
    ]
