# Generated by Django 2.0.2 on 2018-04-29 11:53

from django.db import migrations


def assign_mid(apps, schema_editor):
    EmailPixelUser = apps.get_model('users', 'EmailPixelUser')
    for e in EmailPixelUser.objects.all():
        if e.meeting:
            e.m_id = e.meeting_id
            e.save()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0010_emailpixeluser_m_id'),
    ]

    operations = [
        migrations.RunPython(assign_mid),
    ]
