# Generated by Django 2.0.2 on 2018-04-29 12:39

from django.db import migrations


def assign_community(apps, schema_editor):
    EmailPixelUser = apps.get_model('users', 'EmailPixelUser')
    for e in EmailPixelUser.objects.all():
        if e.meeting:
            e.community = e.meeting.community
            e.save()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0012_emailpixeluser_community'),
    ]

    operations = [
        migrations.RunPython(assign_community),
    ]
