# Generated by Django 2.0.2 on 2018-05-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180429_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('notification_type', models.CharField(choices=[('agenda', 'agenda'), ('protocol', 'protocol'), ('protocol_draft', 'protocol draft')], max_length=100, verbose_name='Notification type')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='Subject')),
                ('recipients', models.TextField(blank=True, null=True, verbose_name='Recipients')),
                ('html', models.TextField(verbose_name='HTML Content')),
            ],
            options={
                'verbose_name': 'Email log',
                'verbose_name_plural': 'Email logs',
            },
        ),
    ]
