# Generated by Django 2.0.2 on 2018-06-17 15:59

from django.db import migrations


def update_pixels(apps, schema_editor):
    EmailPixelUser = apps.get_model('users', 'EmailPixelUser')
    EmailPixelUser.objects.filter(m_id=0).delete()
    EmailPixelUser.objects.filter(community__isnull=True).delete()
    EmailPixelUser.objects.filter(m_id=10).update(m_id=0)


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0014_emaillog'),
    ]

    operations = [
        migrations.RunPython(update_pixels),
    ]
