# Generated by Django 2.0 on 2018-01-29 11:15

import communities.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import ocd.base_models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0002_auto_20171206_1447'),
        ('communities', '0003_auto_20171214_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=ocd.base_models.create_uid, max_length=24, unique=True)),
                ('file', models.FileField(max_length=200, storage=django.core.files.storage.FileSystemStorage('/home/yaniv/Projects/OpComm/uploads'), upload_to=communities.models.meeting_attachment_path, verbose_name='File')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('active', models.BooleanField(default=True)),
                ('ordinal', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='File created at')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attachments', to='communities.Community')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_files_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attachments', to='meetings.Meeting')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
