# Generated by Django 2.0.2 on 2018-06-03 13:16

import communities.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_auto_20180515_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingattachment',
            name='file',
            field=models.FileField(max_length=200, storage=django.core.files.storage.FileSystemStorage('/home/yaniv/Projects/OpComm/uploads'), upload_to=communities.models.meeting_attachment_path, verbose_name='File'),
        ),
    ]
