# Generated by Django 2.0 on 2018-02-15 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ocd.base_models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0002_auto_20171206_1447'),
        ('issues', '0009_auto_20180107_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=ocd.base_models.create_uid, max_length=24, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('version', models.PositiveIntegerField(default=1)),
                ('last_edited_at', models.DateTimeField(auto_now_add=True, verbose_name='Last Edited at')),
                ('content', ocd.base_models.HTMLField(verbose_name='Reference')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='issues.Issue')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references_last_edited', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReferenceRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_versions_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='issues.Reference')),
            ],
        ),
    ]
