# Generated by Django 2.0 on 2018-02-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_auto_20180221_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='title',
            field=models.CharField(max_length=800, verbose_name='Title'),
        ),
    ]
