# Generated by Django 2.0.2 on 2018-06-03 13:16

import django.core.files.storage
from django.db import migrations, models
import issues.models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_auto_20180515_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueattachment',
            name='file',
            field=models.FileField(max_length=200, storage=django.core.files.storage.FileSystemStorage('/home/yaniv/Projects/OpComm/uploads'), upload_to=issues.models.issue_attachment_path, verbose_name='File'),
        ),
    ]
